# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capybara', '3.36'
gem 'pry', '0.14.1'
gem 'cucumber', '5.2'
gem 'faker', '2.19'
gem 'rspec', '3.10'
gem 'mongo', '2.17'
gem 'selenium-webdriver', '4.1'
gem 'allure-cucumber', '2.13.6.4'
